# Generated by Django 5.0.2 on 2024-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('adminuser', 'Adminuser')], max_length=100),
        ),
    ]
